name: GitHub Actions Demo
on:
  push:
jobs:
  Java-Maven-Release:
    name: Java Maven release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Increment patch version
        run: mvn validate -DbumpMinor
