name: GitHub Actions Demo
on:
  push:
jobs:
  Java-Maven-Release:
    name: Java Maven release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install numversion
        run: npm install -g numversion

      - name: Get current version
        id: get_version
        run: echo "::set-output name=current_version::$(numversion get)"

      - name: Increment patch version
        id: increment_version
        run: echo "::set-output name=new_version::$(numversion increment --type patch --input '${{ steps.get_version.outputs.current_version }}')"

      - name: Set new version in environment variable
        run: echo "NEW_VERSION=${{ steps.increment_version.outputs.new_version }}" >> $GITHUB_ENV

      - name: Java Maven release
        uses: qcastel/github-actions-maven-release@v1.12.31
        with:
          version: '${{ env.NEW_VERSION }}'
